### ISSUE TITLE
Timeline keyframes applying last value before playing

### ISSUE THREAD

**Issue by HauntedSmores** [juliangarnier/anime#212] opened 2017-07-24 15:37 UTC
I have a timeline definition:

```
let timeline = anime.timeline({ autoplay: false });
timeline.add({
    targets: '#aye',
    scale: [
        { value: '1', easing: 'linear', duration: 0 },
        { value: '-1, 1', easing: 'linear', duration: 0 },
        { value: '-2, 2', easing: 'easeInCubic', duration: 500 },
        { value: '-1, 1', duration: 1000 }
    ]
});
```

For whatever reason, before the timeline plays, the target is has `scale(-1, 1)` applied even though I'm explicitly defining the timeline to start with the target at `scale(1)`

**Comment by nosugarsociety** [comment] 2017-08-31 01:06
I also have the same trouble. Timeline shows final state at first.
Here is my code example. https://codepen.io/nosugarsociety/pen/eEbZdE

**Comment by juliangarnier** [comment] 2017-09-10 12:36
I can't reproduce.
I don't see any styles applied to the div if the timeline autoplay parameter is set to false.
https://codepen.io/juliangarnier/pen/vJoaed?editors=0010

Also I'm not sure of what you're trying to achieve with two consecutive keyframes with duration: 0.

Maybe it's related to #228?

Closing for now.

**Closed by juliangarnier** 2017-09-10 12:36 UTC

**Comment by HauntedSmores** [comment] 2017-09-13 18:34
@juliangarnier Yeah I was trying to have a couple things happen instantly but I just needed to make the duration 1 instead of 0. Thanks
