### ISSUE TITLE
Stop Anime from running every time when navigating the page?

### ISSUE THREAD

**Issue by MariuzM** [juliangarnier/anime#550] opened 2019-03-05 14:27 UTC
Apologies if this is not the right section for this. But maybe you know how can i stop from AnimeJS running every time when navigating the page, like clicking a menu item that navigates to www.example.com/something.html from www.example.com/index.html.

I have a loading animation and i just want for that to be loaded once when someone just typed www.example.com. So bellow i have tried this code, it was working when visiting for first time (cache cleared) but if i type www.example.com again it's not loading the animation, so maybe there is another way?

```
if (!sessionStorage.isVisited) {
  sessionStorage.isVisited = 'true';
  document.addEventListener('DOMContentLoaded', () => {
    anime({
      targets: '.heading',
      opacity: [0, 1],
      duration: 700,
      easing: 'easeOutCubic'
    });
  });
}
```

**Comment by alexchantastic** [comment] 2019-03-09 07:16
I would consider this a general JS question rather than an anime question.

From what I gather, the issue is that you're storing the fact that the site was visited before firing the animation. The problem is that you're probably caching that setting across sessions.

**Comment by kn0wn** [comment] 2020-03-14 14:39
Hi @MariuzM - This is out of scope for animejs. However to accomplish what you are looking for, you could use localstorage or a cookie to store this information.

**Closed by kn0wn** 2020-03-14 14:39 UTC
